course = " python progRamming "
# c_u = course.upper()
print(course.upper())
print(course.lower())
print(course.title())
print(course.strip())
print(course.lstrip())
print(course.rstrip())
print(course.find("pro"))
print(course.replace("p", "j"))
print("pro" in course)
print("swift" not in course)
print(course.split())
print(course.split("r"))
print(course.split("a"))
print(course.split(" "))
